       SUBROUTINE BCASTP(NDIMN,NNODE,NBNOR,NBNOI,NGEOM,CSAFM,IMMAT,& 
     &           ALPHA,NELEM,NPOIN,NBOUN,MXSID,d,R,M,COMMUNICATOR) 
! 
! *** THIS SUBROUTINE BROADCASTS P-SPACE DATA TO THE SLAVE PROCESSORS 
! 
      IMPLICIT NONE 
      INCLUDE 'mpif.h' 
! 
      INTEGER NDIMN,NNODE,NBNOR,NBNOI,NGEOM,IMMAT,NELEM,MPI_IERR 
      INTEGER NPOIN,MXSID,NBOUN 
      INTEGER COMMUNICATOR
      REAL ALPHA,CSAFM,d,R,M 
! 
      CALL MPI_BCAST(NDIMN,1,MPI_INTEGER,0,COMMUNICATOR,MPI_IERR) 
      CALL MPI_BCAST(NNODE,1,MPI_INTEGER,0,COMMUNICATOR,MPI_IERR)     
      CALL MPI_BCAST(NBNOR,1,MPI_INTEGER,0,COMMUNICATOR,MPI_IERR) 
      CALL MPI_BCAST(NBNOI,1,MPI_INTEGER,0,COMMUNICATOR,MPI_IERR) 
      CALL MPI_BCAST(NGEOM,1,MPI_INTEGER,0,COMMUNICATOR,MPI_IERR) 
      CALL MPI_BCAST(CSAFM,1,MPI_REAL,   0,COMMUNICATOR,MPI_IERR) 
      CALL MPI_BCAST(IMMAT,1,MPI_INTEGER,0,COMMUNICATOR,MPI_IERR) 
      CALL MPI_BCAST(ALPHA,1,MPI_REAL,   0,COMMUNICATOR,MPI_IERR) 
      CALL MPI_BCAST(NELEM,1,MPI_INTEGER,0,COMMUNICATOR,MPI_IERR) 
      CALL MPI_BCAST(NPOIN,1,MPI_INTEGER,0,COMMUNICATOR,MPI_IERR)
      CALL MPI_BCAST(NBOUN,1,MPI_INTEGER,0,COMMUNICATOR,MPI_IERR)
      CALL MPI_BCAST(MXSID,1,MPI_INTEGER,0,COMMUNICATOR,MPI_IERR)
      CALL MPI_BCAST(d,1,MPI_REAL,       0,COMMUNICATOR,MPI_IERR) 
      CALL MPI_BCAST(R,1,MPI_REAL,       0,COMMUNICATOR,MPI_IERR) 
      CALL MPI_BCAST(M,1,MPI_REAL,       0,COMMUNICATOR,MPI_IERR) 
! 
      RETURN 
      END 
 
