         SUBROUTINE GETAVR(NNODE,UNKNO_PP,NELEM_PP,NPOIN_PP,NPOIN,& 
     &        UNKO,INTMA_PP,GEOME_PP,IPCOM_PP,RANK,NGRPS,NPGRP) 
! 
! *** SUBROUTINE TO FIND THE AVERAGE OF THE UNKNOWN VARIABLE AT EACH MESH NODE 
! 
      IMPLICIT NONE 
      INCLUDE 'mpif.h' 
! 
        INTEGER NELEM_PP,NPOIN,NPOIN_PP,IE,IN,IP,INTMA_PP(3,NELEM_PP) 
        INTEGER IP_PP,IG,NNODE,IPCOM_PP(NPOIN_PP),RANK,NGRPS,MPI_IERR 
        INTEGER NPGRP(NGRPS),MPI_STATUS(MPI_STATUS_SIZE),TAG1,TAG2,TAG3 
      	REAL GEOME_PP(7,NELEM_PP),AREA 
        REAL SUMUNKO_PP(NPOIN_PP),FLAG_PP(NPOIN_PP) 
	REAL CO,FLAG(NPOIN),SUMUNKO(NPOIN) 
        REAL UNKO(NPOIN),UNKO_PP(NPOIN_PP),UNKNO_PP(1,3,NELEM_PP),X 
! 
! *** SET FLAG TO ZERO 
! 
        CO=0.0 
        IF(RANK.EQ.0)THEN 
        CALL RFILLV(FLAG,NPOIN,CO) 
        CALL RFILLV(SUMUNKO,NPOIN,CO) 
        ENDIF        !LINKS WITH IF STATEMENT ON LINE 18 
        IF(RANK.NE.0)THEN 
        CALL RFILLV(FLAG_PP,NPOIN_PP,CO) 
        CALL RFILLV(SUMUNKO_PP,NPOIN_PP,CO) 
        ENDIF        !LINKS WITH IF STATEMENT ON LINE 23 
! 
        IF(RANK.NE.0)THEN      !SLAVE PROCESSORS ONLY  
! 
! *** LOOP OVER EACH ELEMENT 
! 
        DO 100 IE=1,NELEM_PP 
! 
! *** ELEMENT AREA TO WEIGHT THE AVERAGE 
! 
        AREA=GEOME_PP(7,IE) 
! 
! *** LOOP OVER EACH ELEMENT NODE 
! 
        DO 200 IN=1,NNODE 
        IP_PP=INTMA_PP(IN,IE) 
        IP=IPCOM_PP(IP_PP) 
        X=UNKNO_PP(1,IN,IE) 
!  	SUMUNKO_PP(IP_PP)=X*AREA+SUMUNKO_PP(IP_PP) 
! 
        FLAG_PP(IP_PP)=FLAG_PP(IP_PP)+AREA 
 200  CONTINUE 
 100  CONTINUE 
! 
! *** SEND SUMUNKO AND FLAG TO MASTER PROCESSOR 
!	 
      TAG1=RANK*100+1 
      TAG2=RANK*100+2 
      TAG3=RANK*100+3 
      CALL MPI_SEND(SUMUNKO_PP,NPOIN_PP,MPI_REAL,0,&  
     &         TAG1, MPI_COMM_WORLD,MPI_IERR) 
      CALL MPI_SEND(FLAG_PP,NPOIN_PP,MPI_REAL,0,& 
     &        TAG2, MPI_COMM_WORLD,MPI_IERR) 
      CALL MPI_SEND(IPCOM_PP,NPOIN_PP,MPI_INTEGER,0,& 
     &        TAG3,MPI_COMM_WORLD,MPI_IERR) 
! 
        ENDIF       !LINKS WITH IF STATEMENT ON LINE 19 
! 
! *** MASTER PROCESSOR COLLECTS LOCAL VECTORS AND ASSEMBLES 
! 
      IF(RANK.EQ.0)THEN 
      DO 400 IG=1,NGRPS 
        NPOIN_PP=NPGRP(IG) 
        CALL RFILLV(FLAG_PP,NPOIN_PP,CO) 
        CALL RFILLV(SUMUNKO_PP,NPOIN_PP,CO) 
! 
        TAG1=100*IG+1 
        TAG2=100*IG+2 
        TAG3=100*IG+3 
        CALL MPI_RECV(SUMUNKO_PP,NPOIN_PP,MPI_REAL,IG,& 
     &           TAG1,MPI_COMM_WORLD,MPI_STATUS,MPI_IERR) 
        CALL MPI_RECV(FLAG_PP,NPOIN_PP,MPI_REAL,IG,& 
     &           TAG2,MPI_COMM_WORLD,MPI_STATUS,MPI_IERR) 
        CALL MPI_RECV(IPCOM_PP,NPOIN_PP,MPI_INTEGER,IG,& 
     &       TAG3,MPI_COMM_WORLD,MPI_STATUS,MPI_IERR) 
        DO 500 IP_PP=1,NPOIN_PP 
            IP=IPCOM_PP(IP_PP) 
            SUMUNKO(IP)=SUMUNKO(IP)+SUMUNKO_PP(IP_PP) 
            FLAG(IP)=FLAG(IP)+FLAG_PP(IP_PP) 
 500  CONTINUE 
 400  CONTINUE 
      ENDIF        !LINKS WITH IF STATEMENT ON LINE 54 
! 
! *** LOOP OVER EACH MESH NODE 
! 
      IF(RANK.EQ.0)THEN 
      DO 300 IP=1,NPOIN 
      UNKO(IP)=SUMUNKO(IP)/FLAG(IP) 
 300  CONTINUE 
      ENDIF 
! 
! *** BROADCAST UNKO TO ALL PROCESSORS 
! 
      CALL MPI_BCAST(UNKO,NPOIN,MPI_REAL,0,&  
     &       MPI_COMM_WORLD,MPI_IERR ) 
!       
      RETURN 
      END 
