      SUBROUTINE GETFLA(NELEM_PP,NNODE,VNPNT,DISNF_PP,FLUXP_PP,& 
     &               FLUYP_PP,UX,UY,IV,VSPACE_FIRST,VSPACE_LAST) 
! 
      INTEGER NNODE,VNPNT,NELEM_PP,IV 
      INTEGER VSPACE_FIRST,VSPACE_LAST
      REAL DISNF_PP(NNODE,VSPACE_FIRST:VSPACE_LAST,NELEM_PP)
      REAL FLUXP_PP(1,3,NELEM_PP),FLUYP_PP(1,3,NELEM_PP) 
      REAL UX,UY,CO 
! *** INITIALISE FLUXP_PP AND FLUYP_PP 
      CO=0.0 
      CALL RFILLA(FLUXP_PP,1,3,NELEM_PP,CO) 
      CALL RFILLA(FLUYP_PP,1,3,NELEM_PP,CO) 
! *** GET THE FLUXES 
        DO 1001 IE=1,NELEM_PP 
        DO 1000 IN=1,3 
! *** DEAL WITH THE CASE OF A VACCUUM (WHEN DISNF_PP IS VERY, VERY SMALL!) 
        TMP=ABS(DISNF_PP(IN,IV,IE)) 
        IF(TMP.EQ.0.0)THEN 
          FLUXP_PP(1,IN,IE)=0.0 
          FLUYP_PP(1,IN,IE)=0.0 
          GOTO 2000 
          ENDIF 
! *** OTHERWISE UNDER NORMAL CIRCUMSTANCES 
      FLUXP_PP(1,IN,IE)=UX*DISNF_PP(IN,IV,IE) 
      FLUYP_PP(1,IN,IE)=UY*DISNF_PP(IN,IV,IE) 
 2000 CONTINUE 
 1000 CONTINUE 
 1001 CONTINUE 
! 
      RETURN 
      END 
