      SUBROUTINE GETFLU(NPOIN,UNKNO,FLUXX,FLUYY,UX,UY) 
! 
      REAL UNKNO(NPOIN) 
      REAL FLUXX(NPOIN),FLUYY(NPOIN) 
      REAL UX,UY,TMP 
! *** THE VALUES OF UX AND UY ARE SET AT THE BEGINNING OF THE MAIN PROGRAM 
      DO 1000 IP=1,NPOIN 
        TMP=ABS(UNKNO(IP)) 
! *** FOR THE CASE OF A VACCUUM (WHEN UNKNO IS VERY, VERY SMALL!) 
        IF(TMP.EQ.0.0)THEN 
          FLUXX(IP)=0.0 
          FLUYY(IP)=0.0 
          GOTO 2000 
        ENDIF 
      FLUXX(IP)=UX*UNKNO(IP) 
      FLUYY(IP)=UY*UNKNO(IP) 
 2000 CONTINUE 
 1000 CONTINUE 
! 
      RETURN 
      END 
