      SUBROUTINE GETMAT(NELEM ,NNODE ,NGEOM ,GEOME, MMAT) 
! 
      REAL GEOME(NGEOM,NELEM),MMAT(NNODE,NELEM) 
! 
! 
! *** CALCULATES THE INVERSE LUMPED MASS MATRIX 
! 
      C24=1./24. 
      C4=4.0 
! 
! *** SET MMAT TO ZERO 
! 
      CALL RFILLM(MMAT,NNODE,NELEM,0.0) 
! 
! *** LOOP OVER THE ELEMENTS 
! 
      DO 1000 IELEM=1,NELEM 
! 
! *** JACOBIAN OF THE ELEMENT 
! 
      RJ =GEOME(7,IELEM) 
      RJ24=RJ*C24 
! 
! *** ADD TO MMAT 
! 
      DO 1020 INODE=1,NNODE 
      MMAT(INODE,IELEM)=MMAT(INODE,IELEM)+C4*RJ24 
 1020 CONTINUE 
! 
! *** END OF LOOP OVER THE ELEMENTS 
! 
 1000 CONTINUE 
! 
! *** INVERSION OF MMAT 
! 
      DO 2010 IELEM=1,NELEM 
      DO 2000 INODE=1,NNODE 
      MMAT(INODE,IELEM)=1./MMAT(INODE,IELEM) 
 2000 CONTINUE 
 2010 CONTINUE 
! 
      RETURN 
      END 
