      SUBROUTINE GETNOR(NDIMN ,NBNOI ,NBNOR ,NPOIN ,NBOUN ,BSIDO ,&
     &                 RSIDO ,COORD,RANK )
!
	IMPLICIT NONE
	INCLUDE 'mpif.h' 
      REAL COORD(NDIMN,NPOIN),RSIDO(NBNOR,NBOUN)
	REAL DX,DY,RL,RT,C10 
! 
	INTEGER NDIMN,NBNOI,NBNOR,NPOIN,NBOUN,RANK
	INTEGER IPOI0,IPOI1,IB,MPI_IERR
      INTEGER BSIDO(NBNOI,NBOUN) 
!
! *** THE NORMALS AND LENGTHS FOR THE OUTER SIDES OF THE REGION 
! 
      C10=1.0 
! 
! *** LOOP OVER THE BOUNDARY SIDES. 
! 
      DO 6531 IB=1,NBOUN 
      IPOI0=BSIDO(1,IB) 
      IPOI1=BSIDO(2,IB) 
      DX=COORD(1,IPOI1)-COORD(1,IPOI0) 
      DY=COORD(2,IPOI1)-COORD(2,IPOI0) 
      RL=SQRT(DX*DX+DY*DY) 
      RT=C10/RL 
      RSIDO(1,IB)= DY*RT 
      RSIDO(2,IB)=-DX*RT 
      RSIDO(3,IB)= RL 
 6531 CONTINUE 
! 
      RETURN 
      END 
