        SUBROUTINE GTEQNF(NFO_PP,NNODE,NELEM_PP,DISND_PP,&
     &                    DISUX_PP,DISUY_PP,DISPS_PP,UX,UY,M)
!
! *** THIS SUBROUTINE CALCULATES THE EQUILIBRIUM NF BASED ON THE DISCONTINUOUS
! *** BULK FLOW CONDITIONS FOR USE IN CALCULATING THE BGK RHS
!
        IMPLICIT NONE
!
        INTEGER NNODE,NELEM_PP,IE,IN
!
        REAL PI,M,BETA2,PS,UX,UY,ND,TMP,CX,CY,NA,MM,RHO
        REAL NFO_PP(NNODE,NELEM_PP),DISND_PP(NNODE,NELEM_PP)
        REAL DISUX_PP(NNODE,NELEM_PP)
        REAL DISUY_PP(NNODE,NELEM_PP),DISPS_PP(NNODE,NELEM_PP)
!
! *** PARAMETERS
!
        PARAMETER(PI=3.1416,NA=6.022e26)
!
! *** INITIALISE
!
        CALL RFILLM(NFO_PP,NNODE,NELEM_PP,0.0)
!
! *** LOOP OVER ALL THE DISCONTINUOUS P-SPACE NODES
!
        DO 1000 IE=1,NELEM_PP
        DO 1001 IN=1,NNODE
        ND=DISND_PP(IN,IE)    !NUMBER DENSITY
        MM=M/NA
        RHO=MM*ND
        PS=DISPS_PP(IN,IE)  !BULK STATIC PRESSURE
        IF(PS.LT.1e-20)GOTO 1003
        CX=DISUX_PP(IN,IE)   !BULK VELOCITIES
        CY=DISUY_PP(IN,IE)
        BETA2=RHO/(2*PS)     !BETA SQUARED
        TMP=-BETA2*((CX-UX)*(CX-UX)+(CY-UY)*(CY-UY))
        NFO_PP(IN,IE)=ND*(BETA2/PI)*EXP(TMP)
 1003 CONTINUE
 1001 CONTINUE
 1000 CONTINUE
!
! *** RETURN TO  ADVNCE
!
        RETURN
        END

